UIHRMP-Serkan/UIHRMP/Areas/EmployeeArea/Controllers/ExpensesController.cs
using HRMP.CORE.Entities;
using HRMP.CORE.Enum;
using HRMP.DAL.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIHRMP.Areas.EmployeeArea.Models;
using UIHRMP.FileManger;

namespace UIHRMP.Areas.EmployeeArea.Controllers
{
    [Area("EmployeeArea")]
    public class ExpensesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ExpensesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }


        // GET: Expenses
        public async Task<IActionResult> Index()
        {
            ViewData["ExpenseTypeID"] = new SelectList(_context.Expenses.OrderBy(x => x.ExpenseType), "ID", "ExpenseTypeName");
            var databaseContext = _context.Expenses.Include(e => e.Employee);
            var vm = new IndexViewModel()
            {
                Expenses = await databaseContext.ToListAsync()
            };
            return View(vm);
        }

        // GET: Expenses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var expense = await _context.Expenses
                .Include(e => e.ExpenseType)
                .Include(e => e.Employee)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);
        }

        // GET: Expenses/Create
        [HttpGet("[controller]/[action]/{Id}")]
        public IActionResult Create(string Id)
        {
            ViewData["ExpenseTypeID"] = new SelectList(_context.Expenses.OrderBy(x => x.ExpenseType), "ID", "ExpenseTypeName");
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IndexViewModel expense)
        {
            if (ModelState.IsValid)
            {
                var enums = ConfirmStatus.Pending;
                var newexpense = new Expense
                {
                    ExpenseDocumentPath = expense.CheckDocument.GetUniqueNameAndSavePhotoToDisk(_webHostEnvironment),
                    ConfirmStatus = enums,
                    Id = Convert.ToInt32(HttpContext.Session.GetString("userId")),
                    ExpenseType = (ExpenseType)expense.ExpenseTypeID,
                    Amount = expense.Amount,
                    DateOfExpense = expense.DateOfExpense,
                    Description = expense.Explanation,
                };
                _context.Add(newexpense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }



            ViewData["ExpenseTypeID"] = new SelectList(_context.Expenses.OrderBy(x => x.ExpenseType), "ID", "ExpenseTypeName", expense.ExpenseTypeID);
            return View(expense);
        }

        //// GET: Expenses/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {

        //        return NotFound();
        //    }

        //    var expense = await _context.Expenses.FindAsync(id);
        //    ExpenseEditVM editVM = new()
        //    {
        //        ID = expense.Id,
        //        Amount = expense.Amount,
        //        CheckDocumentName = expense.CheckDocument,
        //        DateOfExpense = expense.DateOfExpense,
        //        ExpenseTypeID = expense.ExpenseTypeID,
        //        Explanation = expense.Explanation,

        //    };
        //    if (expense == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["ExpenseTypeID"] = new SelectList(_context.ExpenseTypes, "ID", "ExpenseTypeName", expense.ExpenseTypeID);

        //    return View(editVM);
        //}

        //// POST: Expenses/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, ExpenseEditVM editVM)
        //{
        //    var newExpense = await _context.Expenses.FindAsync(id);
        //    if (id != editVM.ID)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        newExpense.Amount = editVM.Amount;
        //        newExpense.DateOfExpense = editVM.DateOfExpense;
        //        newExpense.ExpenseTypeID = editVM.ExpenseTypeID;
        //        newExpense.Explanation = editVM.Explanation;

        //        if (editVM.CheckDocument is not null)
        //        {
        //            newExpense.CheckDocument = editVM.CheckDocument.GetUniqueNameAndSavePhotoToDisk(_webHostEnvironment);
        //            FileManager.RemoveImageFromDisk(editVM.CheckDocumentName, _webHostEnvironment);
        //        }
        //        _context.SaveChanges();
        //        TempData["message"] = "Harcama Güncellendi";
        //        return RedirectToAction("Index", "Expenses", new { Id = HttpContext.Session.GetString("userId") });


        //    }

        //    ViewData["ExpenseTypeID"] = new SelectList(_context.ExpenseTypes, "ID", "ExpenseTypeName");


        //    return View(editVM);
        //}

        //// GET: Expenses/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    var deleted = _context.Expenses.FirstOrDefault(x => x.ID == id);

        //    if (deleted == null)
        //    {
        //        return NotFound();
        //    }
        //    _context.Expenses.Remove(deleted);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction("Index", "Expenses", new { Id = HttpContext.Session.GetString("userId") });
        //}


        private bool ExpenseExists(int id)
        {
            return _context.Expenses.Any(e => e.Id == id);
        }

    }
}

UIHRMP-Serkan/UIHRMP/Areas/EmployeeArea/Views/Expenses/Details.cshtml
@model HRMP.CORE.Entities.Expense

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseContent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfExpense)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfExpense)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConfirmStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConfirmStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpenseDocumentPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpenseDocumentPath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employee.ActivationCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyManager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompanyManager.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsRead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsRead)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UIHRMP-Serkan/UIHRMP/Areas/EmployeeArea/Views/Expenses/Index.cshtml
@using HRMP.CORE.Enum
@model IndexViewModel


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/css/dataTables.bootstrap4.min.css" rel="stylesheet" />


<div class="container-fluid p-2">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-end">
            <h5 class="m-0 p-2 font-weight-bold text-primary">Harcamalarınız</h5>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal1"
                    data-url="@Url.Action("Create")">
                Harcama Ekle
            </button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="myTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Açıklama</th>
                            <th>Harcama Türü</th>
                            <th>Tutar</th>
                            <th>Fiş Tarihi</th>
                            <th>Onay Durumu</th>
                            <th>İşlemler</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Expenses)
                        {
                            <tr>
                                <th>@item.Description</th>
                                <th>@item.ExpenseType.ToString()</th>
                                <th>@item.Amount</th>
                                <th>@item.DateOfExpense.ToString("dd MMMM")</th>
                                <th>@item.ConfirmStatus</th>
                                @if (item.ConfirmStatus == ConfirmStatus.Pending)
                                {
                                    <th class="d-flex justify-content-between"><a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal@(item.Id)">Sil</button></th>
                                    <th></th>
                                    <div class="modal fade" id="exampleModal@(item.Id)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Silme İşlemi</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                </div>
                                                <div class="modal-body">
                                                    Silmek istediğinize emin misiniz? id= @item.Id
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Vazgeç</button>
                                                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <th>Onaylandı.</th>
                                   
                                }

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Harcama Ekleme</h2>
            </div>
            <div class="modal-body">
                <form asp-controller="Expenses" asp-action="Create" enctype="multipart/form-data">

                    <div class="form-group">
                        <label asp-for="CheckDocument" class="control-label">Fatura Belge</label>
                        <div class="custom-file">
                            <input asp-for="CheckDocument" class="custom-file-input" id="customFile" />
                            <label class="custom-file-label" for="customFile">Choose File</label>
                        </div>
                        <span asp-validation-for="CheckDocument" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ExpenseTypeID" class="control-label">Harcama Türü</label>
                        <select asp-for="ExpenseTypeID" class="form-control" asp-items="ViewBag.ExpenseTypeID"></select>
                        <span asp-validation-for="ExpenseTypeID" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Amount" class="control-label"></label>
                        <input type="number" asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Explanation" class="control-label"></label>
                        <textarea maxlength="250" asp-for="Explanation" class="form-control" style="width:100%; height:150px;"></textarea>
                        <span asp-validation-for="Explanation" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfExpense" class="control-label"></label>
                        <input type="date" asp-for="DateOfExpense" class="form-control" value="" />
                        <span asp-validation-for="DateOfExpense" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-primary" />
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section Scripts{
<script type="text/javascript">
    $(document).ready( function () {
    $('#myTable').DataTable({
         "language": {
        "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
    }
    });
    });
</script>
<script type="text/javascript">
    $("custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>
}