UIHRMP-Serkan/UIHRMP/Areas/CompanyManagerArea/Controllers/CompanyManagerController.cs
using HRMP.BLL.Abstract;
using HRMP.BLL.Services.Abstract;
using HRMP.CORE.Entities;
using HRMP.DAL.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using UIHRMP.Areas.CompanyManagerArea.Models;
using UIHRMP.Areas.EmployeeArea.Models;

namespace UIHRMP.Areas.CompanyManagerArea.Controllers
{

    [Area("CompanyManagerArea")]
    public class CompanyManagerController : Controller
    {
        private readonly ICompanyManagerService _companyManagerService;
        private readonly IEmployeeService _employeeService;
        private readonly ApplicationDbContext _context;

        private readonly IAdvancePaymentsService _advancePaymentsService;
        private readonly IExpenseService _expenseService;
        private readonly ILeaveService _leaveService;
        private readonly IMesajService _mesajService;
        private readonly IPackageService packageService;
        private readonly ICompanyService companyService;

        public CompanyManagerController(ICompanyManagerService companyManagerService, ApplicationDbContext context, IEmployeeService employeeService, IAdvancePaymentsService advancePaymentsService, IExpenseService expenseService, ILeaveService leaveService, IMesajService mesajService, IPackageService packageService, ICompanyService companyService)
        {
            _companyManagerService = companyManagerService;
            _context =context;
            _employeeService = employeeService;

            _advancePaymentsService = advancePaymentsService;
            _expenseService = expenseService;
            _leaveService = leaveService;
            _mesajService = mesajService;
            this.packageService = packageService;
            this.companyService = companyService;
        }
        // GET: CompanyManagerController

        public ActionResult Index()
        {
            RequestsVM requests = new RequestsVM();
            requests.Leaves = _leaveService.ListLeaveRequestWithEmployee();
            requests.Advanceds = _advancePaymentsService.ListAdvancePaymentsRequestWithEmployee();
            requests.Expenses = _expenseService.ListAdvanceExpenseWithEmployee();

            int NotificationCount = requests.Leaves.Count() + requests.Advanceds.Count() + requests.Expenses.Count();
            ViewBag.Count = NotificationCount;
            return View(requests);
        }

        public IActionResult ChangePassword()
        {
            ChangePasswordVM change = new ChangePasswordVM();
            return View(change);
        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordVM change)
        {
            var companyManagerPassword = _companyManagerService.GetById((int)HttpContext.Session.GetInt32("managerID")).Password;
            if (ModelState.IsValid) 
            {
                if (change.Password == companyManagerPassword && change.NewPassword == change.NewPasswordControl)
                {
                    bool isDone = _companyManagerService.ChangePassword(companyManagerPassword, change.NewPassword);
                    if (isDone)
                    {
                        TempData["ValidationMessage"] = "Şifre değiştirildi.";
                        return View();
                    }

                }
                else
                {
                    TempData["ValidationMessage"] = "Şifre yanlış girilmiştir.";
                    return View();
                }

            }
            return View();
        }

        public ActionResult EditManager()
        {
            int id = (int)HttpContext.Session.GetInt32("managerID");
            CompanyManager companyManager = _companyManagerService.GetById(id);
            return View(companyManager);
        }

        // POST: CompanyManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditManager(int id, CompanyManager companyManager)
        {
            CompanyManager companyManager2 = _companyManagerService.GetById(id);
            companyManager2.Address = companyManager.Address;
            companyManager2.PhoneNumber = companyManager.PhoneNumber;

            companyManager = companyManager2;

            if (!ModelState.IsValid)
            {
                TempData["Validation"] = "Bilgeler Güncellenemedi!";
                return View();
            }

            _companyManagerService.Update(companyManager2);

            return RedirectToAction(nameof(Listele));
        }
        public ActionResult ManagerDetails()
        {
            int id = (int)HttpContext.Session.GetInt32("managerID");
            CompanyManager companyManager = _companyManagerService.GetById(id);
            return View(companyManager);
        }

        // GET: CompanyManagerController/Details/5
        public ActionResult Details(int id)
        {
            Employee employee = _employeeService.GetById(id);
            return View(employee);
        }

        // GET: CompanyManagerController/Create
        public ActionResult Create()
        {
            EmployeeCreationVM employeeCreationVM = new EmployeeCreationVM();
            return View(employeeCreationVM);
        }

        // POST: CompanyManagerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeCreationVM employeeCreationVM)
        {
            Employee employee = new Employee();
            employee.CompanyManagerID = (int)HttpContext.Session.GetInt32("managerID");
            employee.Email = _employeeService.CreateEmployeeMail(employee.CompanyManagerID, employeeCreationVM.Name, employeeCreationVM.Surname);
            employee.Password = _employeeService.CreateRandomPassword();           
            employee.ActivationCode = "123";
            employee.Address = employeeCreationVM.Address;
            employee.BirthDate = employeeCreationVM.BirthDate;
            employee.PhoneNumber = employeeCreationVM.PhoneNumber;
            employee.Gender = employeeCreationVM.Gender;
            employee.Name = employeeCreationVM.Name;
            employee.Surname = employeeCreationVM.Surname;
            employee.TCNo = employeeCreationVM.TCNo;
            employee.Title = employeeCreationVM.Title;
            employee.HiredDate = employeeCreationVM.HiredDate;
            employee.EmployeePhoto = employeeCreationVM.EmployeePhoto;
            if (employeeCreationVM.EmployeePhoto != null)
            { 
                string ticks = DateTime.Now.Ticks.ToString();
                var path = Directory.GetCurrentDirectory() + @"/wwwroot/img/" + ticks + Path.GetExtension(employeeCreationVM.EmployeePhoto.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    employeeCreationVM.EmployeePhoto.CopyTo(stream);
                }
                
                employeeCreationVM.PhotoPath = @"~/img/" + ticks + Path.GetExtension(employeeCreationVM.EmployeePhoto.FileName);
            }
            
            employee.PhotoPath = employeeCreationVM.PhotoPath;
            if (!ModelState.IsValid)
            {
                TempData["Validation"] = "Çalışan Eklenemedi!";
                return View();
            }

            try
            {
                _employeeService.Add(employee);
                return RedirectToAction(nameof(Listele));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("managerID");
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("usersurname");
            return RedirectToAction("Login", "Home", new { area = "" });
        }


        public ActionResult Listele()
        {
            //CheckActivate();
            int x = (int)HttpContext.Session.GetInt32("managerID");
            IEnumerable<Employee> employees = _employeeService.ListEmployeesByManagerID(x);
            return View(employees);
        }

        public void CheckActivate()
        {
            IEnumerable<Employee> employees = _employeeService.GetAll();
            foreach (var item in employees)
            {
                if (item.HiredDate < DateTime.Now && item.QuitDate > DateTime.Now)
                {
                    item.IsActive = true;
                    _employeeService.Update(item);
                }
                else
                {
                    item.IsActive = false;
                    _employeeService.Update(item);
                }
            }
        }

        // GET: CompanyManagerController/Edit/5
        public ActionResult Edit(int id)
        {
            Employee employee = _employeeService.GetById(id);
            return View(employee);
        } 

        // POST: CompanyManagerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Employee employee)
        {
            Employee employee2 = _employeeService.GetById(id);
            employee2.Address = employee.Address;
            employee2.BirthDate = employee.BirthDate;
            employee2.PhoneNumber = employee.PhoneNumber;
            employee2.Gender = employee.Gender;
            employee2.Name = employee.Name;
            employee2.Surname = employee.Surname;
            employee2.TCNo = employee.TCNo;
            employee2.Title = employee.Title;
            employee2.HiredDate = employee.HiredDate;
            employee2.EmployeePhoto = employee.EmployeePhoto;

            if (!ModelState.IsValid)
            {
                TempData["Validation"] = "Çalışan Güncellenemedi!";
                return View();
            }

            _employeeService.Update(employee2);

            return RedirectToAction(nameof(Listele));
        }

        public IActionResult Advance()
        {

UIHRMP-Serkan/UIHRMP/Areas/CompanyManagerArea/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Etik - @ViewData["Title"]</title>
    <link rel="icon" href="~/img/logo.png"
          type="image/x-icon">


    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">


    <style type="text/css">
        a:hover {
            cursor: pointer;
        }
    </style>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="CompanyManagerArea" asp-controller="CompanyManager" asp-action="Index">
                <div>
                    <img src="~/img/logo.png" width="75px" />
                </div>
                <div class="sidebar-brand-text mx-3">ETİK</div>
            </a>

            <!-- Divider -->
            <!-- Nav Item - Dashboard -->
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-table"></i>
                    <span>PERSONEL</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-action="Create">PERSONEL EKLE</a>
                        <a class="collapse-item" asp-action="Listele">PERSONEL LİSTELE</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>TALEPLER</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-action="Index">BEKLEYEN TALEPLER</a>
                        <a class="collapse-item" asp-action="Leave">İZİNLER</a>
                        <a class="collapse-item" asp-action="Expense">HARCAMALAR</a>
                        <a class="collapse-item" asp-action="Advance">AVANSLAR</a>
                    </div>
                </div>
            </li>

                        <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-table"></i>
                    <span>PAKETLER</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-action="SeeCompanyPackages">PAKETİM</a>
                    </div>
                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div style="font-size:15px" class="sidebar-brand-text mx-3">Şİrket Yönetİcİsİ olarak gİrİş yapıldı.</div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">



            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <!-- Nav Item - Alerts -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-fw"></i>
                                <!-- Counter - Alerts -->
                                <span class="badge badge-danger badge-counter">@ViewBag.Count</span>
                            </a>
                            <!-- Dropdown - Alerts -->
                        </li>

                        <!-- Nav Item - Messages -->
                        <!-- Dropdown - Messages -->
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Context.Session.GetString("username") @Context.Session.GetString("usersurname")</span>
                                <img class="img-profile rounded-circle"
                                     src="@Url.Content(Context.Session.GetString("picPath"))">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-action="ManagerDetails">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profil Bilgileri
                                </a>
                                <a class="dropdown-item" asp-action="EditManager">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Ayarlar
                                </a>
                                <a class="dropdown-item" asp-action="ChangePassword">
                                    <i class="fas fa fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Şifre Değiştir
                                </a>
                                @*<a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Giriş Kayıtları
                                </a>*@
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Çıkış
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; KD9 Team-1 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Çıkılsın mı?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Mevcut oturumunuzu bitirmek istiyorsanız, aşağıdan "Çıkış"ı seçin.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">İptal</button>
                    <a asp-action="Logout" class="btn btn-primary">Çıkış</a>
                </div>
            </div>
        </div>
    </div>

    }

    <!-- Bootstrap core JavaScript-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.js"></script>

    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>

    <script src="~/Login_v2/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Login_v2/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Login_v2/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Login_v2/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>